repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.1
    hooks:
      - id: poetry-check

  - repo: https://github.com/andrei-shabanski/poetry-plugin-sort
    rev: v0.2.0
    hooks:
      - id: poetry-sort

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.286
    hooks:
      - id: ruff
        args:
          - --fix

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-all
          - pydantic==2.3.0
