site_name: Azuma

theme:
  name: "material"

plugins:
  search:
  autorefs:
  mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          show_root_heading: true
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: true

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.extra
