[tool.poetry]
name = "azuma"
version = "0.0.0"
description = "Yet another Sigma library for Python"
authors = ["Manabu Niseki <manabu.niseki@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/ninoseki/azuma"
repository = "https://github.com/ninoseki/azuma"

[tool.poetry.dependencies]
python = "^3.10"
regex = ">=2022"
lark-parser = ">=0.12,<1.0"
pyyaml = ">=6.0,<7.0"
pydantic = ">=1.8,<2.0"

[tool.poetry.group.dev.dependencies]
black = "^23.1"
ci-py = "^1.0.0"
gitpython = "^3.1"
loguru = "^0.6.0"
mypy = "^1.0"
pre-commit = "^3.1"
pytest = "^7.2.1"
pytest-pretty = "^1.1"
pytest-randomly = "^3.12.0"
pyupgrade = "^3.3.1"
ruff = "^0.0.252"
types-pyyaml = "^6.0.12.3"

[tool.poetry-dynamic-versioning]
enable = true

[build-system]
requires = ["poetry-core", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.ruff]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort
    "C",    # flake8-comprehensions
    "B",    # flake8-bugbear
    "T20",  # flake8-print
]
ignore = [
    "E501",  # line too long, handled by black
]
