[tool.poetry]
name = "azuma"
version = "0.0.0"
description = "Yet another Sigma library for Python"
authors = ["Manabu Niseki <manabu.niseki@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/ninoseki/azuma"
repository = "https://github.com/ninoseki/azuma"

[tool.poetry.dependencies]
python = "^3.10"
lark-parser = ">=0.12,<1.0"
loguru = "^0.7"
pydantic = ">=1.8,<2.0"
pyyaml = ">=6.0,<7.0"
regex = ">=2022"
typer = "^0.9.0"

[tool.poetry.group.dev.dependencies]
black = "^23.3"
ci-py = "^1.0.0"
gitpython = "^3.1"
mypy = "^1.4"
pre-commit = "^3.3"
pytest = "^7.4"
pytest-pretty = "^1.2"
pytest-randomly = "^3.12"
pyupgrade = "^3.7"
ruff = "^0.0"
types-pyyaml = "^6.0"
urllib3 = "^1.0"

[tool.poetry.group.doc.dependencies]
mkdocs = "^1.4"
mkdocs-material = "^9.1"
mkdocstrings = {extras = ["python"], version = "^0.22"}

[tool.poetry.scripts]
azuma = "azuma.cli:app"

[tool.poetry-dynamic-versioning]
enable = true

[build-system]
requires = ["poetry-core", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.ruff]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "C",    # flake8-comprehensions
    "B",    # flake8-bugbear
    "T20",  # flake8-print
]
ignore = [
    "E501",  # line too long, handled by black
]
