name: Publish package
on:
  release:
    types: ["created"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.8.2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: poetry
      - name: Install plugin
        run: poetry self add "poetry-dynamic-versioning[plugin]"
      - name: Set PyPI token
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: poetry config pypi-token.pypi $PYPI_TOKEN
      - name: Build and publish
        run: poetry publish --build
